#!/bin/bash -e


dims(){	
	# DESCRIPTION
	#	takes a filename as argument and prints its matrix dimensions
	cols=$( head <$1 -n 1 |  wc -w  )
	rows=$( wc -l <$1 )
	echo "$rows $cols"
}


transpose(){
	# DESCRIPTION: 
	#	takes a filename as argument and transposes its matrix elements

	#number of existing rows = number of new columns
	cols=$( head <$1 -n 1 |  wc -w  )
	rows=$( wc -l <$1 )
	
	#iterate i through cols
	i=0
	while [ $i != $cols ]
	do
	#iterate j through rows
	j=1
		while read -a line
		do
			echo -n -e "${line[$i]}"				#cat ith character of jth row
			[[ $j -lt $rows ]] && echo -e -n "\t"	#tab-separate elements unless its last element	
			j=$(expr $j + 1)
		done <$1
		
		echo ""				#newline
		i=$(expr $i + 1)
	done
}


add() {
	# DESCRIPTION
	#	adds two matrices

	#check if addition is valid
	m1cols=$( head <$1 -n 1 |  wc -w  )
	m2cols=$( head <$2 -n 1 |  wc -w  )
	m1rows=$( wc -l <$1 )
	m2rows=$( wc -l <$2 )

	if [ $m1cols != $m2cols ]; then
		echo "matrices cannot be added" >&2
		exit 4
	elif [ $m1rows != $m2rows ]; then
		echo "matrices cannot be added" >&2
		exit 4
	fi

	#do addition
	counter=0
	while read -a line1
	do
		counter=$(expr $counter + 1 )
		read -a line2 < <( tail -n +$counter $2 )		#read $2 as array starting from line $counter
		for i in ${!line1[@]}							#iterated through line1 without expanding i 
		do
			echo -n $(expr ${line1[$i]} + ${line2[$i]} )
			[[ $i -lt $(expr $m1cols - 1 ) ]] && echo -e -n "\t"  	 	#tab-separate elements unless its last element
		done
		echo ""
	done <$1

}


mean(){
	echo "do mean"
}

multiply() {

	#check if multiplication is valid
	m1cols=$( head <$1 -n 1 |  wc -w  )
	m2cols=$( head <$2 -n 1 |  wc -w  )
	m1rows=$( wc -l <$1 )
	m2rows=$( wc -l <$2 )

	#cols in m1 must equal rows in m2
	if [ $m1cols != $m2rows ]; then
		echo "matrices cannot be multiplied" >&2
		exit 4
	fi


	#clean m1 matrix
	tempm1="tempm1$$"
	while [ -f $tempm1 ]
	do
		tempm1="$tempm1$$"
	done
	touch $tempm1
	#clean up $1 input and save to tempm1
	while read mline ; do
		for x in $mline ; do 
			echo -n -e "$x\t" | cat >>$tempm1
		done
		echo "" | cat >>$tempm1
	done <$1

	#create safe tempfile to store transposed matrix
	temptrans="temptrans$$"
	while [ -f $temptrans ]
	do
		tempMatrix="$temptrans$$"
	done
	touch $temptrans
	transpose $2 | cat >$temptrans
	
	range=$(expr $m1cols - 1)
	for i in $(seq 1 $m1rows ) ; do
		for j in $(seq 1 $m2cols ) ; do
			tabcount=0
			sum=0
			for k in $(seq 1 $m1cols) ; do
				X=$( cat <$tempm1 | cut -f $k | head -n $i | tail -n 1 )
				Y=$( cat <$temptrans | cut -f $k | head -n $j | tail -n 1 )
				echo "X: $X, Y: $Y"
				product=$(expr $X \* $Y )
				sum=$(expr $sum + $product )
			done
			echo -n -e "$sum"
			[[ $tabcount -lt $range ]] && echo -e -n "\t"
		done   
		echo ""
    done 
echo "complete"
}


#PARSE ARGUMENTS
#check single matrix operations
if [ $1 = "dims" ] || [ $1 = "transpose" ] || [ $1 = "mean" ] ; then

	if [ $# = 1 ] ; then
		
		#create safe tempfile to store input matrix
		tempMatrix="tempfile$$"
		while [ -f $tempMatrix ]
		do
			tempMatrix="$tempMatrix$$"
		done
		touch $tempMatrix

		cat >$tempMatrix

		$1 $tempMatrix
	
		rm $tempMatrix -f
		exit 0

	elif [ $# = 2 ]; then
		if [ -f $2 ] ; then
			$1 "$2"
			exit 0
		else 
			echo -e "error opening $2" >&2
			exit 2
		fi
	else
		echo -e "invalid number of arguments" >&2
		exit 1
	fi
#check two matrix operations
elif [ $1 = "add" ] || [ $1 = "multiply" ] ; then
	if [ $# = 3 ]; then
		if [ ! -f $2 ]; then
			echo -e "could not open $2" >&2
			exit 2
		elif [ ! -f $3 ]; then
			echo -e "could not open $3" >&2
			exit 2
		else
			$1 "${@:2}"
			exit 0
		fi
	else
		echo -e "invalid number of arguments" >&2
		exit 1
	fi
else
	echo -e "invalid argument: $1" >&2
	exit 1
fi
